# This is a basic workflow to help you get started with Actions

name: copy
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'copy.txt'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: file copy
        run: cp a.txt copy.txt -f
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply copy

